<a href="https://colab.research.google.com/github/tungts1101/learning_pytorch/blob/master/pytorch_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

np_array = np.array(data)
x_np = torch.from_numpy(np_array)

x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype=torch.float)

print(f"Init Tensor: \n {x_data} \n")
print(f"Ones Tensor: \n {x_ones} \n")
print(f"Random Tensor: \n {x_rand} \n")

Init Tensor: 
 tensor([[1, 2],
        [3, 4]]) 

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4366, 0.2580],
        [0.7411, 0.5747]]) 



In [3]:
tensor = torch.rand(3, 4)
print(f"Shape: {tensor.shape}, Datatype: {tensor.dtype}, Device: {tensor.device}")

Shape: torch.Size([3, 4]), Datatype: torch.float32, Device: cpu
